##配置中心，连接仓库获取配置文件，需要在启动类加入EnableConfigServer并在配置文件中加入git地址
##设置那个配置文件从仓库取就需要将服务的application.yml改为bootstrap.yml,并在其中指定文件名
##在客户端需要导入spring-cloud-starter-config

server:
  port: 7996
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KingAtrophy/MySpringCloudConfig
          username: liyan990113@126.com
          password: 1990113byg
          searchPaths: configClient*
  #用于动态刷新配置文件
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7999/eureka/ #注册到服务注册中心
#用于动态刷新配置文件需要在客户端的controller中加@RefreshScope，并引入
#spring-cloud-starter-config在修改配置文件后需要
#发送post请求到{ip}：{port}/bus/refresh
management:
  security:
  enabled: false

